version: '3.9'

x-base-web: &base-web
    build: .
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      - db

services:
  web:
    <<: *base-web
    ports:
      - "8080:8080"
  
  migrations:
    <<: *base-web
    command: ["./wait-for-it.sh", "db:3306", "--", "flask", "db", "upgrade"]
    depends_on:
      - db
  
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
      

# volumes:
#   postgres_data:
#     name: postgres_data